//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.23 at 01:27:06 AM CEST 
//


package nl.uva.sne.daci._1_0.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://sne.uva.nl/daci/1.0/schema}SubjectAttributes"/>
 *         &lt;element ref="{http://sne.uva.nl/daci/1.0/schema}PermissionAttributes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestType", propOrder = {
    "subjectAttributes",
    "permissionAttributes"
})
public class RequestType {

    @XmlElement(name = "SubjectAttributes", required = true)
    protected AttributesType subjectAttributes;
    @XmlElement(name = "PermissionAttributes", required = true)
    protected AttributesType permissionAttributes;

    /**
     * Gets the value of the subjectAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link AttributesType }
     *     
     */
    public AttributesType getSubjectAttributes() {
        return subjectAttributes;
    }

    /**
     * Sets the value of the subjectAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributesType }
     *     
     */
    public void setSubjectAttributes(AttributesType value) {
        this.subjectAttributes = value;
    }

    /**
     * Gets the value of the permissionAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link AttributesType }
     *     
     */
    public AttributesType getPermissionAttributes() {
        return permissionAttributes;
    }

    /**
     * Sets the value of the permissionAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributesType }
     *     
     */
    public void setPermissionAttributes(AttributesType value) {
        this.permissionAttributes = value;
    }

}
