//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.23 at 01:27:06 AM CEST 
//


package nl.uva.sne.daci._1_0.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.w3._2000._09.xmldsig.KeyInfoType;
import org.w3._2000._09.xmldsig.SignatureType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.uva.sne.daci._1_0.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TenantId_QNAME = new QName("http://sne.uva.nl/daci/1.0/schema", "TenantId");
    private final static QName _Attribute_QNAME = new QName("http://sne.uva.nl/daci/1.0/schema", "Attribute");
    private final static QName _Condition_QNAME = new QName("http://sne.uva.nl/daci/1.0/schema", "Condition");
    private final static QName _Signature_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Signature");
    private final static QName _AttributeValue_QNAME = new QName("http://sne.uva.nl/daci/1.0/schema", "AttributeValue");
    private final static QName _Request_QNAME = new QName("http://sne.uva.nl/daci/1.0/schema", "Request");
    private final static QName _SubjectAttributes_QNAME = new QName("http://sne.uva.nl/daci/1.0/schema", "SubjectAttributes");
    private final static QName _GrantToken_QNAME = new QName("http://sne.uva.nl/daci/1.0/schema", "GrantToken");
    private final static QName _KeyInfo_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyInfo");
    private final static QName _PermissionAttributes_QNAME = new QName("http://sne.uva.nl/daci/1.0/schema", "PermissionAttributes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.uva.sne.daci._1_0.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConditionType }
     * 
     */
    public ConditionType createConditionType() {
        return new ConditionType();
    }

    /**
     * Create an instance of {@link GrantTokenType }
     * 
     */
    public GrantTokenType createGrantTokenType() {
        return new GrantTokenType();
    }

    /**
     * Create an instance of {@link AttributesType }
     * 
     */
    public AttributesType createAttributesType() {
        return new AttributesType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link AttributeValueType }
     * 
     */
    public AttributeValueType createAttributeValueType() {
        return new AttributeValueType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sne.uva.nl/daci/1.0/schema", name = "TenantId")
    public JAXBElement<String> createTenantId(String value) {
        return new JAXBElement<String>(_TenantId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sne.uva.nl/daci/1.0/schema", name = "Attribute")
    public JAXBElement<AttributeType> createAttribute(AttributeType value) {
        return new JAXBElement<AttributeType>(_Attribute_QNAME, AttributeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConditionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sne.uva.nl/daci/1.0/schema", name = "Condition")
    public JAXBElement<ConditionType> createCondition(ConditionType value) {
        return new JAXBElement<ConditionType>(_Condition_QNAME, ConditionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Signature")
    public JAXBElement<SignatureType> createSignature(SignatureType value) {
        return new JAXBElement<SignatureType>(_Signature_QNAME, SignatureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sne.uva.nl/daci/1.0/schema", name = "AttributeValue")
    public JAXBElement<AttributeValueType> createAttributeValue(AttributeValueType value) {
        return new JAXBElement<AttributeValueType>(_AttributeValue_QNAME, AttributeValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sne.uva.nl/daci/1.0/schema", name = "Request")
    public JAXBElement<RequestType> createRequest(RequestType value) {
        return new JAXBElement<RequestType>(_Request_QNAME, RequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sne.uva.nl/daci/1.0/schema", name = "SubjectAttributes")
    public JAXBElement<AttributesType> createSubjectAttributes(AttributesType value) {
        return new JAXBElement<AttributesType>(_SubjectAttributes_QNAME, AttributesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GrantTokenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sne.uva.nl/daci/1.0/schema", name = "GrantToken")
    public JAXBElement<GrantTokenType> createGrantToken(GrantTokenType value) {
        return new JAXBElement<GrantTokenType>(_GrantToken_QNAME, GrantTokenType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "KeyInfo")
    public JAXBElement<KeyInfoType> createKeyInfo(KeyInfoType value) {
        return new JAXBElement<KeyInfoType>(_KeyInfo_QNAME, KeyInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sne.uva.nl/daci/1.0/schema", name = "PermissionAttributes")
    public JAXBElement<AttributesType> createPermissionAttributes(AttributesType value) {
        return new JAXBElement<AttributesType>(_PermissionAttributes_QNAME, AttributesType.class, null, value);
    }

}
